### ISSUE TITLE
New Relic Airflow Plugin failed for version 1.10.11

### ISSUE THREAD

**Issue by EbenShea** [newrelic/newrelic-airflow-plugin#11]
Is there a new Airflow plugin available for New Relic or revised marshmallow package that doesn't result in the error below.  Some language around deprecation at the bottom may be the culprit:

[2020-08-03 13:59:22,093] {plugins_manager.py:112} ERROR - Failed to import plugin newrelic_plugin
Traceback (most recent call last):
  File "/home/AirflowAdmin/.local/lib/python2.7/site-packages/airflow/plugins_manager.py", line 106, in load_entrypoint_plugins
    plugin_obj = entry_point.load()
  File "/home/AirflowAdmin/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/home/AirflowAdmin/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/AirflowAdmin/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (marshmallow 2.21.0 (/home/AirflowAdmin/.local/lib/python2.7/site-packages), Requirement.parse('marshmallow<2.20,>=2.18.0'), set(['flask-appbuilder']))
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Airflow 1.10 will be the last release series to support Python 2
1.10.11

**Comment by a-feld** [comment]
Hi @EbenShea I'm not sure how the New Relic plugin plays into this error message, but based on the error message `Requirement.parse('marshmallow<2.20,>=2.18.0')` you should hopefully be able to run `pip install -U 'marshmallow<2.20'` in your environment to resolve the conflict. The airflow plugin doesn't depend on `marshmallow` directly so it shouldn't be causing the problem, despite the error occurring on plugin load.

The plugin's dependencies can be [seen on github](https://github.com/newrelic/newrelic-airflow-plugin/network/dependencies).  Please post here again if there continue to be issues.
