### ISSUE TITLE
NEW_RELIC_INSERT_KEY causing plugin import failure

### ISSUE THREAD

**Issue by hazhhajian** [newrelic/newrelic-airflow-plugin#40]
I am trying to integrate Newrelic Airflow plugin with Airflow 2.6.1 running on Python 3.9 or 3.11. In both python versions whenever I specify NEW_RELIC_INSERT_KEY as ENV variable it throughs the following error

` ERROR - Failed to import plugin newrelic_plugin
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.9/site-packages/airflow/plugins_manager.py", line 230, in load_entrypoint_plugins
    if not is_valid_plugin(plugin_class):
  File "/opt/app-root/lib64/python3.9/site-packages/airflow/plugins_manager.py", line 201, in is_valid_plugin
    plugin_obj.validate()
  File "/opt/app-root/lib64/python3.9/site-packages/newrelic_airflow_plugin/newrelic_plugin.py", line 131, in validate
    setattr(Stats, attr, getattr(NewRelicStatsLogger, attr))
AttributeError: 'NoneType' object has no attribute 'incr'`

Here is how I run the Airflow container

`podman run -d -it --rm \
-p 8086:8080 \
-v /tmp/airflow_mount:/opt/airflow \
--env 'NEW_RELIC_INSERT_KEY=xxxxxx' \
--env 'NEW_RELIC_SERVICE_NAME=xxxxxx' \
--env 'NEW_RELIC_HOST=metric-api.eu.newrelic.com' \
airflow
`
If I remove "NEW_RELIC_INSERT_KEY" the plugin loads with no error.

Any hints or help is highly appreciated. Thank you.

**Comment by winniewytong** [comment]
We are experiencing the same issue. Has anyone figured a way to fix it yet?
